#+TITLE: OrgPy	
#+AUTHOR:	github/dfoyle
#+STARTUP:	content

~OrgPy~ is a simple collection of a class and assorted methods and functions, spun out of some personal interest in manipulating org files. Check out [[http://www.orgmode.org][org-mode]] for more details on how an org file is organized.

This is a *beginner* project by an aspiring programmer. It's very likely to have some silly bugs and mistakes, and a somewhat lousy attempt at keeping a doc file. Don't forget to backup your org file before trying out the script.

* Features

The script is quite light on features at the moment. Here are some of the things it can do.

- Reading an ~.org~ file into a DocNode class. Each headline is an ElementNode object. Both ElementNode and DocNode has children attributes as well some others.
- Support for following attributes: stars, parent, children, title.
- ~.org~ file settings and stuff that comes before the first headline are kept,respectively, at DocNode's settings and header attributes. 

* Usage

Eventually ~OrgPy~ will be a command line script used for quick captures into a specified org file. In addition, it'll probably have some focus in exporting into other formats, especially into a [[http://www.sfwa.org/2005/01/the-obligatory-manuscript-format-article/][manuscript format]] appropriate for short stories and novels.

** Basic usage

*Running the script in python interpreter.*
#+BEGIN_SRC bash
$ python -i org.py
#+END_SRC

This opens the script in the interpreter and allows you to call the functions. Eventually ~main()~ will contain more than just a simple call.

*Parsing an org file into DocNode object*
#+BEGIN_SRC python
doc = parse_file(filename)
#+END_SRC

*Listing headings.*
#+BEGIN_SRC python
list_items(doc)
#+END_SRC

*Adding a new heading.*
#+BEGIN_SRC python
add_headline(parent, title)
#+END_SRC

